/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-pke
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PKE_API_H
#define INCLUDED_PKE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_pke_EXPORTS
#define PKE_API __GR_ATTR_EXPORT
#else
#define PKE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PKE_API_H */
